name: Paroquia_Sao_Jose
description: "Paroquia São José"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  html: ^0.15.0
  path_provider: ^2.0.5
  syncfusion_flutter_pdfviewer: ^24.2.8  # Versão anterior compatível com firebase_database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
