// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCArdydFnChaAJB4g-Qi9fEV9TVfOh_E',
    appId: '1:10120062313:web:2600977bd6999a4f8009f8',
    messagingSenderId: '10120062313',
    projectId: 'santuariosaofrancis',
    authDomain: 'santuariosaofrancis.firebaseapp.com',
    storageBucket: 'santuariosaofrancis.appspot.com',
    measurementId: 'G-JQJCE4VMEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH-Bm557XZOMfMUdyHFqqckj7g0JY_c7I',
    appId: '1:10120062313:android:cde57f5e98b344c28009f8',
    messagingSenderId: '10120062313',
    projectId: 'santuariosaofrancis',
    storageBucket: 'santuariosaofrancis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjNMsDtlMQzYRN0N1WbRWwMvZh7MFUC7I',
    appId: '1:10120062313:ios:fcdfbada8a7a1b098009f8',
    messagingSenderId: '10120062313',
    projectId: 'santuariosaofrancis',
    storageBucket: 'santuariosaofrancis.appspot.com',
    iosBundleId: 'com.example.missaDiariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjNMsDtlMQzYRN0N1WbRWwMvZh7MFUC7I',
    appId: '1:10120062313:ios:4cc62a82c64c0c2a8009f8',
    messagingSenderId: '10120062313',
    projectId: 'santuariosaofrancis',
    storageBucket: 'santuariosaofrancis.appspot.com',
    iosBundleId: 'com.example.missaDiariaApp.RunnerTests',
  );
}
